### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by Kirk300** [songhwanjun/MEDUSA#1]
I‘m very interested in your work, and can not to find you paper in Google Scholar.
Could you please put the download link here?

**Comment by songhwanjun** [comment]
The paper is not publicly released at BMVC (so slow). Please download our paper below

https://github.com/songhwanjun/songhwanjun.github.io/raw/master/files/2021_BMVC_MEDUSA.pdf

Thanks for your interest!
